blank_issues_enabled: false
contact_links:
  - name: "Official Discord mod"
    url: https://discord.gg/NACSGxNQ5v
    about: Here you can ask your questions about the mod, as well as see full information about it!
